version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - "dependencies"
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    schedule:
      interval: monthly
    directory: '/'
    labels:
      - "dependencies"
    open-pull-requests-limit: 20
