export const CASTLE_TERRACE_PHASE = Object.freeze({
  DORMANT: "dormant",
  SERVANT_ENTER: "servant-enter",
  FURNISH: "furnish",
  POUR: "pour",
  SERVANT_EXIT: "servant-exit",
  ROYAL_ENTER: "royal-enter",
  SETTLE: "settle",
  ACTIVITY: "activity",
  RISE: "rise",
  ROYAL_EXIT: "royal-exit",
  CLEANUP_DELAY: "cleanup-delay",
  SERVANT_RETURN: "servant-return",
  PACK: "pack",
  SERVANT_LEAVE: "servant-leave",
});
