export const HERO_ANIMATION = Object.freeze({
  IDLE: "Idle",
  WALK: "Walk",
  RUN: "Run",
  JUMP: "Jump",
  FALL_DEATH: "FallDeath",
  RESPAWN: "Respawn",
  DODGE_FORWARD: "DodgeForward",
  DODGE_BACKWARD: "DodgeBackward",
  DODGE_LEFT: "DodgeLeft",
  DODGE_RIGHT: "DodgeRight",
  BLOCKED_PUSH: "BlockedPush",
  EDGE_REFUSE_LEFT: "EdgeRefuseLeft",
  EDGE_REFUSE_RIGHT: "EdgeRefuseRight",
  REPELLED: "Repelled",
  SUMMON_AXE: "SummonAxe",
  DISMISS_AXE: "DismissAxe",
  CHOP_LOW: "ChopLow",
  CHOP_MIDDLE: "ChopMiddle",
  CHOP_HIGH: "ChopHigh",
  BORED_LOOK: "BoredLook",
  BORED_STRETCH: "BoredStretch",
  BORED_TAP: "BoredTap",
});
