export const HERO_ACTION = Object.freeze({
  EXPLORING: "exploring",
  BOOSTING_COUNTRY_FINANCES: "boostingCountryFinances",
  USING_TOOL: "usingTool",
  COLLECTING: "collecting",
  INVENTORY_FULL_REACTION: "inventoryFullReaction",
  DODGING: "dodging",
  REPELLED: "repelled",
  EDGE_REFUSAL: "edgeRefusal",
  HOLE_REFUSAL: "holeRefusal",
  BLOCKED_DIG_REACTION: "blockedDigReaction",
  PAT_REACTION: "patReaction",
  ANGRY_ESCAPE: "angryEscape",
  DROWNING: "drowning",
  BRIDGE_CLIMB: "bridgeClimb",
  FALLING_TO_DEATH: "fallingToDeath",
  BURNING: "burning",
  RESPAWNING: "respawning",
  GAME_OVER: "gameOver",
});
