name: Automerge

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.triggering_actor == 'dependabot[bot]' }}
    name: Merge
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Find the pull request
        id: find_pr
        uses: juliangruber/find-pull-request-action@v1
        with:
          branch: ${{ github.event.workflow_run.head_branch }}
        
      - name: Checkouting code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
        
      - name: Merge pull request
        env:
          PR_URL: ${{ steps.find_pr.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: gh pr merge --merge
