name: Autofix

on:
  push:
    branches:
      - master

concurrency:
  group: "autofix-${{ github.ref_name }}"
  cancel-in-progress: false

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier check
        run: yarn prettier --check "**/*.{js,vue,scss}" --ignore-path .gitignore
