name: CI
on:
  push:
    branches:
      - master

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install node modules...
        run: yarn install
      
      - name: Trying to fix lint files...
        run: yarn lint --fix
        
      - name: Autocommiting autofixes changes...
        if: contains(github.ref, 'master') != 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Autofixes with lint automatically applied fixes
          file_pattern: src/
          
      - name: Cache data for future steps
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ github.sha }}
          
  lint:
      runs-on: ubuntu-latest
      needs: autofix
      steps:
      
        - name: Use cached data
          uses: actions/cache@v2
          id: cache
          with:
            path: .
            key: ${{ github.sha }}        
            
        - name: LINT
          run: yarn lint  

  dependabot:
    needs: lint
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: ${{ github.actor == 'dependabot[bot]' and contains(github.ref, 'master') != 'true' }}
    steps:
      # This first step will fail if there's no metadata and so the approval
      # will not occur.
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # Here the PR gets approved.
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Finally, this sets the PR to allow auto-merging for patch and minor
      # updates if all checks pass
      - name: Enable auto-merge for Dependabot PRs
        # if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

  build_and_deploy:
      runs-on: ubuntu-latest
      needs: lint
      if: contains(github.ref, 'master') == 'true'
      steps:
      
        - name: Use cached data
          uses: actions/cache@v2
          with:
            path: .
            key: ${{ github.sha }}        
            
        - name: Build
          run: yarn quasar build
          
        - name: Cache data for future steps
          uses: actions/cache@v2
          with:
            path: .
            key: ${{ github.sha }}

        - name: Deploy to GitHub Pages
          if: success()
          uses: crazy-max/ghaction-github-pages@v2
          with:
            target_branch: gh-pages
            build_dir: build
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
