name: Dependabot Auto Merge

on:
  workflow_run:
    workflows: 
      - "Tests"
    types:
      - completed

jobs:
  dependabot-auto-merge:
    if: github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Label Pull Request
        uses: jburgess/AddRemovePrLabels@v1.0.4
        with:
          githubToken: ${{ github.token }}
          labelsToAdd: automerge

      - name: Auto-merge dependabot PRs
        uses: gsoc2/automerge-action@v0.16.2
        with:
          merge_method: squash
          skip_ci: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
