name: Tests

on:
  pull_request:

concurrency:
  group: "test-${{ github.event.pull_request.head.ref }}"
  cancel-in-progress: false

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Quasar E2E tests
        run: yarn test:e2e:ci

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test/cypress/e2e/screenshots
            test/cypress/e2e/videos
